### ISSUE TITLE
handle unit function

### ISSUE THREAD

**Issue by guillaumeduhamel** [edukera/archetype-lang#253] opened 2021-11-02 15:01 UTC
tests/proposal/unit_function.arl
```
archetype unit_function

variable r : nat = 0

function f() {
  dorequire(r = 1, "error")
}

entry exec() {
  f();
  r := 1
}

entry exec2() {
  f();
  r := 2
}
```

**Comment by rognierbenoit** [comment] 2022-03-14 17:20
duplicate of #231

**Closed by rognierbenoit** 2022-03-14 17:20 UTC
Labels: enhancement, typing, minor
